version: '3.8'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9-management
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./src/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - rabbitmq_network

  producer:
    image: producer
    build:
      context: ./src/producer
      dockerfile: Dockerfile
    environment:
      # APPLICATION
      - CALLBACK_URL=http://producer:8000/receive/
      - TIMEOUT=4
      # RABBITMQ
      - HOSTNAMERABBIT=rabbitmq
      - RABBITMQ_DEFAULT_USER=local_jobs
      - RABBITMQ_DEFAULT_PASS=password
    ports: 
      - "8000:8000"
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq
    networks:
      - rabbitmq_network

  consumer:
    image: consumer
    build:
      context: ./src/consumer
      dockerfile: Dockerfile
    environment:
      # APPLICATION
      - MAX_BATCH_SIZE=8
      - BATCH_TIMEOUT=8
      # RABBITMQ
      - HOSTNAMERABBIT=rabbitmq
      - RABBITMQ_DEFAULT_USER=local_jobs
      - RABBITMQ_DEFAULT_PASS=password
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
